export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST";
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS";
export const CREATE_TWEET_FAIL = "CREATE_TWEET_FAIL";
export const GET_TIMELINE_TWEETS_REQUEST = "GET_TIMELINE_TWEETS_REQUEST";
export const GET_TIMELINE_TWEETS_SUCCESS = "GET_TIMELINE_TWEETS_SUCCESS";
export const GET_TIMELINE_TWEETS_FAIL = "GET_TIMELINE_TWEETS_FAIL";
export const GET_USER_TWEETS_REQUEST = "GET_USER_TWEETS_REQUEST";
export const GET_USER_TWEETS_SUCCESS = "GET_USER_TWEETS_SUCCESS";
export const GET_USER_TWEETS_FAIL = "GET_USER_TWEETS_FAIL";
export const GET_CLICKED_USER_TWEETS_REQUEST =
  "GET_CLICKED_USER_TWEETS_REQUEST";
export const GET_CLICKED_USER_TWEETS_SUCCESS =
  "GET_CLICKED_USER_TWEETS_SUCCESS";
export const GET_CLICKED_USER_TWEETS_FAIL = "GET_CLICKED_USER_TWEETS_FAIL";

export const RETWEET_TWEET_REQUEST = "RETWEET_TWEET_REQUEST";
export const RETWEET_TWEET_SUCCESS = "RETWEET_TWEET_SUCCESS";
export const RETWEET_TWEET_FAIL = "RETWEET_TWEET_FAIL";
export const LIKE_TWEET_REQUEST = "LIKE_TWEET_REQUEST";
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAIL = "LIKE_TWEET_FAIL";
